### ISSUE TITLE
Missing null check on Canvas context

### ISSUE THREAD

**Issue by ghost** [ashish-chopra/ngx-gauge#37] opened 2018-09-12 10:38 UTC
Sometimes I get this error
`ERROR TypeError: "this._context is null"
_clearwebpack-internal:///../../../../ngx-gauge/ngx-gauge.es5.js:209:9_drawShellwebpack-internal:///../../../../ngx-gauge/ngx-gauge.es5.js:195:9animatewebpack-internal:///../../../../ngx-gauge/ngx-gauge.es5.js:296:13requestIDwebpack-internal:///../../../../ngx-gauge/ngx-gauge.es5.js:298:88invokeTaskwebpack-internal:///../../../../zone.js/dist/zone.js:421:17onInvokeTaskwebpack-internal:///../../../core/esm5/core.js:4952:24invokeTaskwebpack-internal:///../../../../zone.js/dist/zone.js:420:17runTaskwebpack-internal:///../../../../zone.js/dist/zone.js:188:28invokeTaskwebpack-internal:///../../../../zone.js/dist/zone.js:496:24invokewebpack-internal:///../../../../zone.js/dist/zone.js:485:28timerwebpack-internal:///../../../../zone.js/dist/zone.js:2025:17 core.js:1448
`

I think the problem is a missing null check when _context is initialized and used
https://github.com/ashish-chopra/ngx-gauge/blob/74a9fd0b9f123362d21a5a7d79b985c0f6a761dc/libs/ngx-gauge/src/gauge/gauge.ts#L205

After I get the error, the gauges work anyway. Maybe Angular reloads them

**Comment by ashish-chopra** [comment] 2019-06-01 05:07
Hi @ghost

The issue is fixed in the current release v1.0.0-beta.8
Please update your dependency and feel free to open the issue if the problem still persists.

**Closed as completed by ashish-chopra** 2019-06-01 05:07 UTC
