### ISSUE TITLE
has no exported member 'ɵɵDirectiveDefWithMeta'

### ISSUE THREAD

**Issue by ravikarthi** [ashish-chopra/ngx-gauge#56] opened 2019-11-05 09:42 UTC
After integrating ngx-gauge library my app throws exception below

ERROR in node_modules/ngx-gauge/gauge/gauge-directives.d.ts(3,35): error TS2694: Namespace has no exported member 'ɵɵDirectiveDefWithMeta'.

Kindly guide me to solve this issue

**Comment by RichardBoyder** [comment] 2019-11-06 09:17
This also happens to me... After updating to latest. Please help

**Comment by RichardBoyder** [comment] 2019-11-08 09:54
Hi guys any news on this?  @ashish-chopra

**Comment by ashish-chopra** [comment] 2019-11-08 09:56
Hi Richard,

I will look into this issue on weekend.

Hopefully will get some solution. But if you have a solution feel free to
send a PR.

Cheers
Ashish

**Comment by RichardBoyder** [comment] 2019-11-08 10:12
sure not a problem. thankyou again for you great plugin and all the hard work

**Comment by nfacha** [comment] 2019-11-09 19:16
Also having this issues

**Comment by akashsherkar** [comment] 2019-11-14 07:23
Also having the same issue. 
It's breaking my project which is about to go live.
Please help

**Comment by Mark0047** [comment] 2019-11-24 13:42
I am also having this issue

**Comment by gb37064** [comment] 2019-12-04 15:15
Same issue.  Following this thread.  BTW I dropped back to the previous version for the time being. Fixed the issue, and my gauge works fine too.

**Comment by qutayba** [comment] 2019-12-11 16:27
> Same issue. Following this thread. BTW I dropped back to the previous version for the time being. Fixed the issue, and my gauge works fine too.

Same here. I downgraded to the previous version 1.0.0-beta.10 and now its working.

**Comment by Shadowzee** [comment] 2019-12-18 15:48
Any lead on this? getting same issue.

**Comment by Shadowzee** [comment] 2019-12-18 15:49
Hi @qutayba  downgrading the version doesn't work for me!!

**Comment by qutayba** [comment] 2019-12-18 18:19
> 
> 
> Hi @qutayba downgrading the version doesn't work for me!!

In my case downgrading was a fix for the error. I hope we get some updates about the issue soon.

**Comment by ashish-chopra** [comment] 2020-02-11 06:22
Hello All,

I am not able to reproduce this error, for me, it is working fine. Kindly share details to reproduce the error. However, I have published v1.0.0-beta.12 which removed Ivy compiled files from the build, but not sure if that fixed this issue or not. Let me know, or I will close this issue.

**Closed as completed** 2020-02-14 04:44 UTC
