### ISSUE TITLE
Gauge Meter is not Updated

### ISSUE THREAD

**Issue by nivu** [ashish-chopra/ngx-gauge#24] opened 2018-05-07 14:57 UTC
While updating the value, only the label alone gets updated, drawing is not happening.

**Comment by nivu** [comment] 2018-05-07 15:18
Value and Meter is not dynamically updated

**Comment by fernandocode** [comment] 2018-05-07 17:22
@navneetnivu07 You could create an example of the problem at https://stackblitz.com/edit/angular-kaonzk?

**Comment by nivu** [comment] 2018-05-07 20:02
@fernandocode In the dev environment, the value alone is updated but the bar didn't update the new value.
But after creating a production build and deploying it works fine.

**Comment by nivu** [comment] 2018-05-07 20:04
@fernandocode I think some others also facing this issue! Check issues #20(Value drops to 0 after animation). I faced the similar problem.

**Comment by ashish-chopra** [comment] 2018-05-09 16:50
Closing this issue. As pointed out as duplicate of #20

**Closed as completed by ashish-chopra** 2018-05-09 16:50 UTC
