### ISSUE TITLE
There was a issue in ngx-gauge with Angular 9 version .

### ISSUE THREAD

**Issue by loveparmar3799** [ashish-chopra/ngx-gauge#67] opened 2020-02-08 12:05 UTC
ERROR in ./node_modules/ngx-gauge/__ivy_ngcc__/fesm2015/ngx-gauge.js 535:144-152
"export 'Renderer' was not found in '@angular/core'
ERROR in ./node_modules/ngx-gauge/__ivy_ngcc__/fesm2015/ngx-gauge.js 607:12-20
"export 'Renderer' was not found in '@angular/core'
ERROR in ./node_modules/ngx-gauge/__ivy_ngcc__/fesm2015/ngx-gauge.js 651:67-75
"export 'Renderer' was not found in '@angular/core'
    
    ERROR in node_modules/ngx-gauge/gauge/gauge.d.ts:1:25 - error TS2724: Module '"C:/Users/parma/OneDrive/Desktop/Projects/Antonic/antonic-backpanel-frontend/node_modules/@angular/co
re/core"' has no exported member 'Renderer'.
import { SimpleChanges, Renderer, AfterViewInit, ElementRef, OnChanges, OnDestroy } from '@angular/core';
                              ~~~~~~~~
    
      node_modules/@angular/core/core.d.ts:5691:31
        5691 export declare abstract class Renderer2 {
                                           ~~~~~~~~~
        'Renderer2' is declared here.
@fernandocode @ashish-chopra

**Comment by fernandocode** [comment] 2020-02-10 11:14
@loveparmar3799 ,

I think the problem is with the update of Renderer2, which will be solved with [this PR](https://github.com/ashish-chopra/ngx-gauge/pull/59#issue-343270228).

There is also [this powershell script](https://github.com/ashish-chopra/ngx-gauge/issues/65#issuecomment-576703563) that can be used to make the correction while the PR is not accepted.

**Comment by Brachacz** [comment] 2020-02-10 17:55
+1 would love to see that merged

**Comment by jkzlouw** [comment] 2020-02-11 10:21
Agreed with WojciechSlyp - change references to Renderer2 for clean compile, but now have run-time errors on usage of ngx-gauge.

**Comment by ashish-chopra** [comment] 2020-02-14 07:56
Thank you everyone for submitting the workaround before me accepting the PR. Sorry for the delay. Since now Angular 9 is out, I have upgraded it to angular 9, download the latest version `v1.0.0` (no beta) for Angular 9. I will publish new minor releases with additional issue fixes in the coming days.

**Closed as completed by ashish-chopra** 2020-02-14 07:56 UTC
