### ISSUE TITLE
Min/Max gauge value doesn't work correctly after updating the value

### ISSUE THREAD

**Issue by Jay031** [ashish-chopra/ngx-gauge#42] opened 2019-04-18 09:22 UTC
Hi all,

I use my gauge to let a user enter a number between i.e. 35 and 75.
The default value is 60 (which is on 50% of the gauge) this works.
After I put it on "61" the gauge fills up completely, it now responds to the difference of the min and max. as in: "75-35 = 40", the Gauge range now goes from 0-40 , so 40 - 75 is showing a full gauge. The ng-reflect-min / max and aria-valuemin are still 35 and 75.

Can anyone help me with this problem?
Thanks in advance

**Comment by fernandocode** [comment] 2019-04-18 11:20
You could add an example of your problem so that we can reproduce it to better understand. I created [this StackBlitz already with the ngx-gauge configured](https://stackblitz.com/edit/angular-j7c783?file=src%2Fapp%2Fapp.component.ts).

**Comment by Jay031** [comment] 2019-04-18 11:40
> You could add an example of your problem so that we can reproduce it to better understand. I created [this StackBlitz already with the ngx-gauge configured](https://stackblitz.com/edit/angular-j7c783?file=src%2Fapp%2Fapp.component.ts).

Hi FernandoCode, 

here's my example, simply click on the gauge to change the number to a random number of this array:
`const VALID_NUMBERS = [35,40,45,50,55,60,65,70,75];`

https://stackblitz.com/edit/angular-mtfgvu

***edit* I've edited it to change to 35 after each number to make it easier to test**

At first you wil see that '40' is almost at the beginning of the gauge (like 10-15%)
That's right, because min=35 and max =75
When you change the number ONCE the gauge will then respond as if min = 0 and max = 40.
You will see that 40 or higher = full gauge, 35 (lowest possible number is around 90%

**Comment by fernandocode** [comment] 2019-04-18 14:44
It really seems that there is a bug when using custom min and max, I tried to check here if I identified the problem but it seems to be something in the calculations, which I'm not aware of, let's see if the component author can verify. If I have time in the future I can try to look more calmly, but I'm fine. Or if you have priority over this try to check if you find the problem and send a PR.

**Comment by ashish-chopra** [comment] 2019-06-01 06:32
The issue has been identified and I am fixing it. I will make a new release this weekend with a fix. Thanks @Jay031 and @fernandocode

**Comment by ashish-chopra** [comment] 2019-06-02 01:34
@Jay031  and @fernandocode, The issue has been fixed in v1.0.0-beta.9
Please update your dependencies.

Thanks!

**Closed as completed by ashish-chopra** 2019-06-02 01:34 UTC
Labels: bug
