### ISSUE TITLE
gauge display not updating when tab is not active

### ISSUE THREAD

**Issue by YacineGameDev** [ashish-chopra/ngx-gauge#29] opened 2018-05-30 15:36 UTC
I just figured that the gauge is not updating the display when we change tabs. 

If you have: `
thresholds =  {
            '20': {color: 'orange'},
            '30': {color: 'orangeRed'},
            '40': {color: 'red'}
        };`

For example if the value of the gauge is 20, you change to another tab for 1-2 minutes and you come back then the displayed value is 50 but the color of the gauge is still orange and at the same level as 20. Hope it's clear enough.

**Comment by ashish-chopra** [comment] 2018-05-30 17:28
Kindly reproduce the issue in a stackblitz and share here.

**Comment by YacineGameDev** [comment] 2018-05-30 19:34
I realized that the issue was in my code, I wasn't changing in a proper manner the value of the gauge. The problem is fixed.

**Comment by YacineGameDev** [comment] 2018-05-30 20:25
Actually I thought it was fixed, here is a stackblitz for this issue: https://stackblitz.com/edit/angular-z9ck3s

to see the issue you have to:
1 - click on "Open in New window" in the top right corner
2- leave the tab and go to another one for like 30 seconds/ 1 minute
3- come back to the tab and you'll notice the issue

![capture](https://user-images.githubusercontent.com/23528812/40746806-6204bed6-6429-11e8-9ff0-bd4f84f4b468.PNG)

In this snapshot between 1000 and 1500 the color of the gauge should be orangeRed. Moreover, the max value is 2000 and here you can see that 1024 filled the gauge till the quarter, it should be in the middle of the gauge.

**Comment by isoengas** [comment] 2018-05-31 10:32
Could this be related to issue #20? The gauge bar value depends on the animation being succesfully executed, but when in the background tab, the browser does not execute the animation and the gauge bar keeps the previous value.. 

Just guessing..

**Comment by YacineGameDev** [comment] 2018-05-31 13:15
So is there a way to execute the animation even in the background tab?

**Comment by YacineGameDev** [comment] 2018-05-31 13:56
Here is a gif showing the issue: (in the black screen i switched to another tab)

![ezgif com-resize](https://user-images.githubusercontent.com/23528812/40786303-bd28f090-64b8-11e8-84a4-d3d14c12c5c3.gif)

**Comment by ashish-chopra** [comment] 2018-05-31 16:56
You mean to say, when value updates the gauge travels to the actual value range but return to original position. Can you please share the reproduced code for this issue on stackblitz?

**Comment by YacineGameDev** [comment] 2018-05-31 17:06
Already did, in this comment : https://github.com/ashish-chopra/ngx-gauge/issues/29#issuecomment-393306471

**Comment by fernandocode** [comment] 2018-06-01 12:41
I added a copy of the [ngx-gauge component in the example](https://stackblitz.com/edit/angular-zntvbh?file=src%2Fngx-gauge%2Fgauge%2Fgauge.ts) to remove the animation and find out if the problem is caused by the animation (which I think it is), I just did not have the time (nor ability) to convert canvas update logic, without the animation, so if someone wants and can do it, and share here the result would be very useful to walk in order to solve the problem.

Example with ngx-gauge: https://stackblitz.com/edit/angular-zntvbh?file=src%2Fngx-gauge%2Fgauge%2Fgauge.ts

**Comment by YacineGameDev** [comment] 2018-06-01 15:09
I think i may have found the issue, it's the call of requestAnimationFrame in the _create function:

`self._animationRequestID = window.requestAnimationFrame((timestamp) =>{
        startTime = timestamp || new Date().getTime();
       animate(timestamp);
      })`

I noticed that when the tab is inactive ( background tab) the function `animate(timestamp)`, used as a callback in the requestAnimationFrame, is never called.

Here is a stackblitz with the modification: https://stackblitz.com/edit/angular-jd7env
When the attribute animation is set to false it's working good (except the fact that the gauge is not animated anymore obviously)
In my case, I don't really need the animation, so it would be nice if we can have a version where we can disable it.

**Comment by fernandocode** [comment] 2018-06-01 19:08
I find it interesting to put the option to activate or deactivate animations, even for performance reasons. (Nice work @Observablerxjs :clap:, could include, try to submit this as PR).

But in addition it is important to identify the cause of the problem and verify a possible solution for the background animations.

**Comment by YacineGameDev** [comment] 2018-06-05 13:15
@fernandocode is there a way I can use the version with the animation option (#31) ? Or  do I have to wait for the pull request to be checked and approved?

**Comment by fernandocode** [comment] 2018-06-05 13:49
@ashish-chopra  will have to approve your PR, and still release a next version with it. 
But while this does not occur, in another situation I send a PR from some library I need the change to my implementation I create a Fork and do the implementation (create a package with ng-packagr (there is a script in that library to generate the package: `build:lib`)). You do not even need to do the publishing in NPM, you can use it locally.
@Observablerxjs

**Comment by YacineGameDev** [comment] 2018-06-05 13:58
ok thanks, it's working :smiley:

**Comment by isoengas** [comment] 2018-06-05 15:27
Anyone willing to try this?

https://stackblitz.com/edit/angular-wzixgj?file=src/ngx-gauge/gauge/gauge.ts

Looks like it's working fine for me... just some minor changes in the animate function

**Comment by YacineGameDev** [comment] 2018-06-05 16:05
yees it's perfect! Good Job @isoengas :clap: :clap:

**Comment by isoengas** [comment] 2018-06-06 11:21
I'll try to make a PR with my changes later today. I think this fixes also issue #20 (which I opened some time ago)

**Comment by AcmeEngineering** [comment] 2018-06-07 16:05
@ashish-chopra  can you consider approve @isoengas's PR #35 and publish the new version on NPM because it really fix this bug. thanks

**Comment by ashish-chopra** [comment] 2018-06-08 17:01
Thank you guys for solving the issue. I will take this PR next week for review.

**Comment by YacineGameDev** [comment] 2018-06-19 13:09
any updates about the PR @ashish-chopra ?

**Comment by YacineGameDev** [comment] 2018-07-10 14:48
is an updated release planned shortly?

**Comment by YacineGameDev** [comment] 2018-09-20 21:02
@isoengas I was implementing your solution when a mountain of errors appeared in my console :smile:.
I figured out where the error comes from but I am not sure about how to fix it.
Here is a stackblitz: https://stackblitz.com/edit/angular-qjrccv
There is one step to reproduce the issue: navigate quickly between the 2 tabs. you'll see the amount of errors at the bottom-right corner of the preview window increasing very fast.
The issue is when angular destroys the component where the gauge is but the gauge was still 'moving'.
This issue is not present in @ashish-chopra 's version.

**Comment by isoengas** [comment] 2018-09-24 10:40
> @isoengas I was implementing your solution when a mountain of errors appeared in my console 😄.
> I figured out where the error comes from but I am not sure about how to fix it.
> Here is a stackblitz: https://stackblitz.com/edit/angular-qjrccv
> There is one step to reproduce the issue: navigate quickly between the 2 tabs. you'll see the amount of errors at the bottom-right corner of the preview window increasing very fast.
> The issue is when angular destroys the component where the gauge is but the gauge was still 'moving'.
> This issue is not present in @ashish-chopra 's version.

Resolved in the last version of my PR

**Comment by ashish-chopra** [comment] 2018-12-25 09:38
Hello Everyone,

I have gone through the conversations here and found that adding a new animation property is useful in crisis situations where you want to disable animation for bug or for any other reason. 

Checkout the README, i have added `animate` property and disables the animation when this property is false. By default it is true. Update your package to 1.0.0-beta.7 to get these changes which are now compatible with Angular 7+. Also, the source code structure is updated according to angular CLI 7. 
Thanks to @Observablerxjs and @flakolefluk for their pull requests which are collectively suggested the changes i pulled into the repo.

For the rest of this issue in which animation code is buggy, i am looking into it and review the PR submitted by @isoengas

**Comment by ashish-chopra** [comment] 2018-12-25 09:41
I didn't see the PR yet, but after reading the conversations, i realize you are trying to run `requestAnimationFrame` even in the background which actually kills the whole reason of using `requestAnimationFrame`. instead of using setTimeOut i used requestAnimationFrame because i do not want to run animation unnecessarily and block the browser resources for it.

**Comment by isoengas** [comment] 2019-01-08 12:22
No, my PR actualy does not change requestAnimationFrame for setTimeout... please  @ashish-chopra have a look at the code.

**Comment by ashish-chopra** [comment] 2019-06-01 05:04
Hi @Observablerxjs,

Hello All,
The issue is fixed in the latest release v1.0.0-beta.8 here:
https://github.com/ashish-chopra/ngx-gauge/releases/tag/v1.0.0-beta.8

Please update ngx-gauge in your project and verify.

Thanks!

**Closed as completed by ashish-chopra** 2019-06-01 05:04 UTC
Labels: bug
