### ISSUE TITLE
Cannot read property 'clearRect' of undefined

### ISSUE THREAD

**Issue by nsathya1990** [ashish-chopra/ngx-gauge#40] opened 2019-03-26 09:56 UTC
I am using ngx-gauge inside ngu-carousel.
I have made gauges inside carousel, which moves left and right. When the page loads for the first time, everything works perfectly. But, when I filter the carousel, I get errors relating to gauge.

ERROR TypeError: Cannot read property 'clearRect' of undefined
    at NgxGauge.push../node_modules/ngx-gauge/fesm5/ngx-gauge.js.NgxGauge._clear (ngx-gauge.js:326)

Could you tell me the cause and suggest any solution for this?

HTML Code:
```
<div class="row">
  <div class="col-lg-12 col-md-12" id="gauge-wrapper">
    <ngu-carousel #myCarousel [inputs]="carouselTile" [dataSource]="carouselTileItems">
      <ngu-tile *nguCarouselDef="let item; let i = index">
        <div class="tile">
          <ngx-gauge [type]="gaugeConfig.gaugeType" [value]="item?.headroom_percent" [label]="gaugeConfig.gaugeLabel"
            [append]="gaugeConfig.gaugeAppendText" [foregroundColor]="item?.colour" [size]=160>
          </ngx-gauge>
          <h6>{{ item?.name }}</h6>
        </div>
      </ngu-tile>
      <button NguCarouselPrev id="leftBtn" class="leftRs" [style.opacity]="myCarousel.isFirst ? 0.5:1">&lt;</button>
      <button NguCarouselNext id="rightBtn" class="rightRs" [style.opacity]="myCarousel.isLast ? 0.5:1">&gt;</button>
    </ngu-carousel>
  </div>
</div>
```

**Comment by PauloMarinho9** [comment] 2019-03-26 12:34
There is a pull request associated to this problem:

https://github.com/ashish-chopra/ngx-gauge/pull/39

**Comment by nsathya1990** [comment] 2019-03-26 13:00
I couldn't understand this. I am little new to Angular. What I am supposed to do here? Could you please explain.
Am I suppose to update my ngx-gauge package?

**Comment by nsathya1990** [comment] 2019-03-26 13:00
> There is a pull request associated to this problem:
> 
> #39

I couldn't understand this. I am little new to Angular. What I am supposed to do here? Could you please explain.

**Comment by ashish-chopra** [comment] 2019-06-01 05:06
@nsathya1990 The issue is fixed in current release v1.0.0-beta.8
Kindly update the library and verify. Feel free to open the issue, if the problem still persists.

**Closed as completed by ashish-chopra** 2019-06-01 05:06 UTC

**Comment by GMAkshayBhat** [comment] 2020-06-24 10:11
**@ashish-chopra** I have updated the library to v1.0.0-beta.8 but also getting same error,can u help me out

**Comment by monstrfolk** [comment] 2024-11-15 19:50
This is still an issue. Getting error with Angular 18 and version 10
